// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj0aKY9jbUPOVV5q-7m0gGLE4S0PUqn5U',
    appId: '1:228791069592:web:202236897d869f717b99ed',
    messagingSenderId: '228791069592',
    projectId: 'menumee-4740b',
    authDomain: 'menumee-4740b.firebaseapp.com',
    storageBucket: 'menumee-4740b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSITBV7pjMHYOINi1QpBEzrgxXN9s8AF8',
    appId: '1:228791069592:android:0f5fe93552a000007b99ed',
    messagingSenderId: '228791069592',
    projectId: 'menumee-4740b',
    storageBucket: 'menumee-4740b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuQaX9_6_XAACgVOt17zEkerl3DpdnVz8',
    appId: '1:228791069592:ios:06403513a933b6657b99ed',
    messagingSenderId: '228791069592',
    projectId: 'menumee-4740b',
    storageBucket: 'menumee-4740b.appspot.com',
    iosBundleId: 'com.example.foodService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuQaX9_6_XAACgVOt17zEkerl3DpdnVz8',
    appId: '1:228791069592:ios:0b4f7fbee86c68e67b99ed',
    messagingSenderId: '228791069592',
    projectId: 'menumee-4740b',
    storageBucket: 'menumee-4740b.appspot.com',
    iosBundleId: 'com.example.foodService.RunnerTests',
  );
}
